In [107]:
import pandas as pd
import numpy as np

In [108]:
df = pd.read_csv("employees_100.csv")
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

### Finding missing values

In [109]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [110]:
# Dropping rows with null values
df2 = df.dropna()
df2

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
6,123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...,...
93,183,Deepak Nayak,Marketing,Hyderabad,28.0,62393,2,5,13,2020-08-09
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [111]:
df2.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [112]:
# Dropping null values for a specific column
df2 = df.dropna(subset = ['city'])
df2

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
...,...,...,...,...,...,...,...,...,...,...
94,121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [113]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

## Filling null values

In [114]:
df['age'] = df['age'].fillna(df['age'].mean())

In [115]:
df['salary'] = df['salary'].str.replace(',', '', regex = False)
df['salary'] = pd.to_numeric(df['salary'], errors= 'coerce')
df['salary'] = df['salary'].fillna(df['salary'].median())

In [116]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [117]:
df['department'].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [118]:
df['department'] = df['department'].fillna(df['department'].mode()[0])

In [119]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [120]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

## Duplicates

In [121]:
df.duplicated().sum()

np.int64(0)

In [122]:
df = df.reset_index()
df.duplicated(subset = ['employee_id']).sum()

np.int64(4)

In [123]:
df.drop_duplicates(subset = ['employee_id'], keep = "first")

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05
2,2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
4,4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...,...
95,95,161,Nikhil Nair,MARKETING,Chennai,22.000000,55740.0,0,5,22,2020-04-22
96,96,172,Neha Desai,HR,Chennai,22.000000,52250.0,0,5,7,2020-11-14
97,97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06
98,98,193,Priya Nayak,HR,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07
99,99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25

## Changing Data Types

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               100 non-null    int64
 1   employee_id         100 non-null    int64
 2   name                100 non-null    str
 3   department          100 non-null    str
 4   city                100 non-null    str
 5   age                 100 non-null    float64
 6   salary              100 non-null    float64
 7   experience          100 non-null    int64
 8   performance_score   100 non-null    int64
 9   projects_completed  100 non-null    int64
 10  joining_date        100 non-null    str
dtypes: float64(2), int64(5), str(4)
memory usage: 8.7 KB

In [125]:
df['joining_date'] = pd.to_datetime(df['joining_date'])
df.head()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05
2,2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
4,4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25

In [126]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               100 non-null    int64
 1   employee_id         100 non-null    int64
 2   name                100 non-null    str
 3   department          100 non-null    str
 4   city                100 non-null    str
 5   age                 100 non-null    float64
 6   salary              100 non-null    float64
 7   experience          100 non-null    int64
 8   performance_score   100 non-null    int64
 9   projects_completed  100 non-null    int64
 10  joining_date        100 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(5), str(3)
memory usage: 8.7 KB

## Renaming Columns

In [127]:
df.rename(columns = {"emp_name": "employee_name"}, inplace = True)

In [128]:
# Cleaning every column names:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [129]:
df.head()

,index,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05
2,2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
4,4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25

In [130]:
# Cleaning inconsistent text
df['department'] = df['department'].str.strip().str.title()
print(df['department'].unique())

<StringArray>
['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing', 'Finance']
Length: 6, dtype: str