In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('employees_100.csv')
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

## Creating new Column:

In [16]:
df['salary'] = df['salary'].str.replace(',', '', regex = False)
df['salary'] = pd.to_numeric(df['salary'], errors= 'coerce')
df['salary'] = df['salary'].fillna(df['salary'].median(), inplace = True)

/tmp/ipykernel_754684/1752583037.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['salary'] = df['salary'].fillna(df['salary'].median(), inplace = True)

In [17]:
df['annual_salary'] = df['salary'] * 12

In [18]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0

## Apply() function

In [19]:
def categorize(num):
    if num > 5:
        return "Experienced Candidate"
    elif num <= 5:
        return "Learner"

df['experience_status'] = df['experience'].apply(categorize)
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,Learner
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,Learner
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,Learner
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,Learner
4,145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate

## Map Function

In [27]:
department_codes = {
    "engineering": "ENG",
    "marketing": "MKT",
    "finance": "FIN",
    "data science": "DAS"
}

df["department_codes"] = df['department'].str.lower().map(department_codes)
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,department_codes
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719.0,5,5,6,2021-07-02,848628.0,Learner,DAS
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058.0,1,8,8,2024-02-05,924696.0,Learner,ENG
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911.0,0,6,18,2019-04-24,838932.0,Learner,DAS
3,146,Neha Das,Engineering,Pune,28.0,69993.0,3,8,1,2022-12-13,839916.0,Learner,ENG
4,145,Isha Nair,Data Science,NaN,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced Candidate,DAS