In [64]:
import numpy as np
import pandas as pd

In [65]:
df = pd.read_csv('employees_100.csv')
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

## Sorting:

In [66]:
df.sort_values(by = "salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
26,141,Manish Kulkarni,HR,Chennai,27.0,"45,835",3,8,13,2022-07-21
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822,4,5,4,2022-06-24
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693,0,4,7,2018-08-27
67,169,Swati Chatterjee,HR,Pune,33.0,49801,3,6,11,2021-08-20
7,181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
...,...,...,...,...,...,...,...,...,...,...
23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06

In [67]:
df.sort_values(by = 'salary', ascending=False)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,5,19,2021-02-26
75,158,Tanvi Malhotra,NaN,Mumbai,32.0,"88,366",11,6,17,2021-02-26
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
...,...,...,...,...,...,...,...,...,...,...
23,143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
45,120,Isha Gupta,Marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
60,157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06

In [68]:
df['department'] = df['department'].str.strip().str.lower()

In [69]:
# Department A - Z, salary high-to-low:
df.sort_values(
    by = ['department', 'salary'],
    ascending = [True, False]
)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
4,145,Isha Nair,data science,NaN,32.0,88216,8,8,14,2019-11-25
88,124,Deepak Verma,data science,Hyderabad,41.0,86380,9,7,8,2024-06-05
59,190,Swati Bose,data science,Mumbai,22.0,78465,0,8,18,2022-11-22
24,170,Rahul Nair,data science,Kolkata,30.0,76425,5,2,4,2021-06-25
54,109,Rohan Kulkarni,data science,Delhi,28.0,76267,5,6,3,2023-01-24
...,...,...,...,...,...,...,...,...,...,...
91,175,Aman Nayak,NaN,NaN,27.0,69076,5,5,10,2019-09-15
81,185,Vikram Desai,NaN,Pune,39.0,68197,9,4,9,2024-09-13
32,186,Rohan Kapoor,NaN,Pune,36.0,65152,8,7,4,2020-02-15
61,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
80,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07

## Ranking

In [70]:
df.drop_duplicates(subset = ['employee_id'], keep = "first", inplace=True)

In [71]:
df['salary'] = df['salary'].str.strip().str.replace(",", "")

df['salary_rank'] = df['salary'].rank(ascending = False)
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank
0,184,Swati Kapoor,data science,Kolkata,38.0,70719,5,5,6,2021-07-02,26.0
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05,13.0
2,171,Manish Desai,data science,Hyderabad,23.0,69911,0,6,18,2019-04-24,28.0
3,146,Neha Das,engineering,Pune,28.0,69993,3,8,1,2022-12-13,27.0
4,145,Isha Nair,data science,NaN,32.0,88216,8,8,14,2019-11-25,2.0
...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,marketing,Chennai,22.0,55740,0,5,22,2020-04-22,74.0
96,172,Neha Desai,hr,Chennai,22.0,52250,0,5,7,2020-11-14,82.0
97,115,Neha Reddy,marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN
98,193,Priya Nayak,hr,NaN,23.0,56821,3,9,16,2019-08-07,68.0
99,152,Kavya Joshi,marketing,Delhi,44.0,69499,10,7,4,2022-03-25,30.0

In [72]:
df.sort_values(by = 'salary_rank')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,88366,11,5,19,2021-02-26,1.0
4,145,Isha Nair,data science,NaN,32.0,88216,8,8,14,2019-11-25,2.0
88,124,Deepak Verma,data science,Hyderabad,41.0,86380,9,7,8,2024-06-05,3.0
84,102,Rahul Menon,engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07,4.0
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255,1,8,19,2021-12-05,5.0
...,...,...,...,...,...,...,...,...,...,...,...
23,143,Neha Rao,sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15,NaN
45,120,Isha Gupta,marketing,Mumbai,26.0,NaN,6,5,14,2018-03-27,NaN
55,179,Arjun Das,finance,NaN,43.0,NaN,10,7,11,2024-08-25,NaN
60,157,Ananya Rao,engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07,NaN
97,115,Neha Reddy,marketing,Chennai,43.0,NaN,12,4,10,2019-06-06,NaN

## Top and Bottom Records

In [73]:
df['salary'] = df['salary'].str.replace(',', '', regex = False)
df['salary'] = pd.to_numeric(df['salary'], errors= 'coerce')
df['salary'] = df['salary'].fillna(df['salary'].median(), inplace = True)

/tmp/ipykernel_798917/1752583037.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['salary'] = df['salary'].fillna(df['salary'].median(), inplace = True)

In [74]:
df.nlargest(5, 'salary')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank
74,158,Tanvi Malhotra,NaN,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1.0
4,145,Isha Nair,data science,NaN,32.0,88216.0,8,8,14,2019-11-25,2.0
88,124,Deepak Verma,data science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,3.0
84,102,Rahul Menon,engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,4.0
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,5.0

In [75]:
df.nsmallest(5, 'performance_score')

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,salary_rank
20,156,Aditya Kapoor,data science,Kolkata,26.0,69765.0,0,2,4,2020-04-12,29.0
24,170,Rahul Nair,data science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,14.0
50,125,Sneha Bose,marketing,Mumbai,32.0,56627.0,7,2,9,2023-07-12,69.0
76,176,Shreya Menon,finance,NaN,41.0,80597.0,9,2,18,2024-11-09,7.0
12,174,Divya Chatterjee,finance,Kolkata,24.0,58374.0,1,3,12,2018-09-21,63.0